import type { Metadata } from 'next';
import { Tiro_Bangla } from 'next/font/google';
import './globals.css';

const tiro = Tiro_Bangla({
   subsets: ['bengali'],
   weight: ['400'],
});

export const metadata: Metadata = {
   title: 'সলাত',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="bn">
         <body className={`${tiro.className} antialiased`}>{children}</body>
      </html>
   );
}
